### ISSUE TITLE
Last watering

### ISSUE THREAD

**Issue by CloudWolf99** [sebr/bhyve-home-assistant#13]
Getting last watering date and time value.

**Comment by sebr** [comment]
This is not straightforward with bhyve. Can you keep track using a tempate sensor?

**Comment by texiun** [comment]
Evening Seb! I was just looking through the https://techsupport.orbitbhyve.com/ (Which is what orbit provided we use rather than their own system) and i noticed there's an option of Watering history. 

Could this be useful?
![WaterHistory](https://user-images.githubusercontent.com/538668/83001005-79d33700-a04e-11ea-897d-130e4f514c7c.png)

**Comment by sebr** [comment]
Yep this could be used. Would you expect it as an attribute on the `zone` or as it's own `sensor` attribute?

**Comment by sebr** [comment]
Released in v2.0.0
