### ISSUE TITLE
async_setup_platforms will fail in 2023.3

### ISSUE THREAD

**Issue by ndoggac** [sebr/bhyve-home-assistant#169]
Getting this log warning.

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for bhyve using this method at custom_components/bhyve/__init__.py, line 124: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by Ace0510** [comment]
I have the same warning.
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 11:24:35 AM (1 occurrences)
Last logged: 11:24:35 AM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for bhyve using this method at custom_components/bhyve/__init__.py, line 124: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by TeodoroLio** [comment]
Same here - thanks for the great work on this integration!

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 2:12:00 PM (1 occurrences)
Last logged: 2:12:00 PM

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for bhyve using this method at custom_components/bhyve/__init__.py, line 124: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by rikpal865** [comment]
Morning, I've the same issue, thanks in advance for this great integration, hoping this specific issue too will be solved soon.

**Comment by sebr** [comment]
Fixed in 3.1.2. Thanks for the report 😄

**Comment by ndoggac** [comment]
Thanks for the fix, and the wonderful integration!
