### ISSUE TITLE
next_start_time seems to be last run time

### ISSUE THREAD

**Issue by jhemak** [sebr/bhyve-home-assistant#245]
**Describe the bug**
The value of the attribute next_start_time appears to be the last time the zone ran, not the next time it will run

**Expected behaviour**
The value of next_start_time should be the next scheduled run time, similar to what is shown in the native app

**BHyve devices**
hose timer

**Device Diagnostics**

**Comment by sebr** [comment]
The value of this attribute is not calculated - it's read directly from the BHyve API. If you are seeing incorrect data you will need to provide more details, such as screenshots along with device diagnostics - the instructions for generating were in the template when you created the issue. If you edit the description you will see them again.

**Comment by mash2k3** [comment]
> **Describe the bug** The value of the attribute next_start_time appears to be the last time the zone ran, not the next time it will run
> 
> **Expected behaviour** The value of next_start_time should be the next scheduled run time, similar to what is shown in the native app
> 
> **BHyve devices** hose timer
> 
> **Device Diagnostics**

I believe this issue was present last season too. After a scheduled watering is complete wait 10 minutes and reload the integration. If the integration updates next scheduled time with correct value you can just create an automation to reload integration after watering is complete. I have not enabled smart watering this season because we are getting lots of rain here.
Let me know if it works.
